file_processing_controllers:
    resource: ../src/Application/CsvProcessing/UI/Http/Controller/
    type: attribute

menu_admin_controllers:
    resource: ../src/Application/Menu/UI/Http/Controller/
    type: attribute
