framework:
    messenger:
        transports:
            async_row: '%env(MESSENGER_TRANSPORT_DSN)%'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:

            App\Application\CsvProcessing\Command\UploadCsvFileCommand: async
            App\Domain\CsvProcessing\Event\CsvFileUploadedEvent: async
            App\Infrastructure\Consumer\CsvFileConsumer: async§
            App\Domain\CsvProcessing\Event\CsvRowProcessedEvent: async_row
