framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: csv_processing
                        type: direct
        routing:
            'App\Domain\CsvProcessing\Event\CsvFileUploadedEvent': async
