name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  tools: composer, phpstan, php-cs-fixer
                  extensions: mbstring, xml, ctype, iconv, pdo_mysql

            - name: Install dependencies
              run: cd shop && composer install --prefer-dist

            - name: Run PHPStan
              run: cd shop && vendor/bin/phpstan analyse --configuration=phpstan.neon

            - name: Run PHP CS Fixer
              run: cd shop && php-cs-fixer fix --dry-run --diff --config=.php-cs-fixer.php

            - name: Run PHPUnit tests
              run: cd shop && vendor/bin/phpunit --configuration=phpunit.xml
